"""Shared control protocol constants for SoftBot ROS topics."""

# Chamber selection.
CHAMBER_BLOCKED = 0
CHAMBER_A = 1
CHAMBER_B = 2
CHAMBER_AB = 3
VALID_CHAMBERS = (CHAMBER_BLOCKED, CHAMBER_A, CHAMBER_B, CHAMBER_AB)

# Pressure control modes.
MODE_STOP = 0
MODE_PID_INFLATE = 1
MODE_PID_SUCTION = -1
MODE_PWM_INFLATE = 2
MODE_PWM_SUCTION = -2
MODE_TANK_FILL = 3
MODE_VENT = 4
MODE_PID_INFLATE_TURBO = 5
MODE_HARDWARE_DIAGNOSTIC = 9

# Hardware diagnostic bitmask for /hardware_test.
HW_PUMP_INFLATE_MAIN = 1 << 0
HW_PUMP_INFLATE_AUX = 1 << 1
HW_PUMP_SUCTION_MAIN = 1 << 2
HW_PUMP_SUCTION_AUX = 1 << 3
HW_VALVE_INFLATE = 1 << 4
HW_VALVE_SUCTION = 1 << 5
HW_VALVE_BOOST = 1 << 6
HW_MUX_CHAMBER_A = 1 << 7
HW_MUX_CHAMBER_B = 1 << 8

MODE_LABELS = {
    MODE_STOP: "STOP",
    MODE_PID_INFLATE: "PID_INFLATE",
    MODE_PID_SUCTION: "PID_SUCTION",
    MODE_PWM_INFLATE: "PWM_INFLATE",
    MODE_PWM_SUCTION: "PWM_SUCTION",
    MODE_TANK_FILL: "TANK_FILL",
    MODE_VENT: "VENT",
    MODE_PID_INFLATE_TURBO: "PID_INFLATE_TURBO",
    MODE_HARDWARE_DIAGNOSTIC: "HARDWARE_DIAGNOSTIC",
}
