"""Shared control protocol constants for SoftBot ROS topics."""

# Chamber selection.
CHAMBER_BLOCKED = 0
CHAMBER_A = 1
CHAMBER_B = 2
CHAMBER_AB = 3
VALID_CHAMBERS = (CHAMBER_BLOCKED, CHAMBER_A, CHAMBER_B, CHAMBER_AB)

# Pressure control modes.
MODE_STOP = 0
MODE_PID_INFLATE = 1
MODE_PID_SUCTION = -1
MODE_PWM_INFLATE = 2
MODE_PWM_SUCTION = -2
MODE_TANK_FILL = 3
MODE_VENT = 4
MODE_PID_INFLATE_TURBO = 5

MODE_LABELS = {
    MODE_STOP: "STOP",
    MODE_PID_INFLATE: "PID_INFLATE",
    MODE_PID_SUCTION: "PID_SUCTION",
    MODE_PWM_INFLATE: "PWM_INFLATE",
    MODE_PWM_SUCTION: "PWM_SUCTION",
    MODE_TANK_FILL: "TANK_FILL",
    MODE_VENT: "VENT",
    MODE_PID_INFLATE_TURBO: "PID_INFLATE_TURBO",
}
